# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=100)),
                ('last_fetched', models.DateTimeField()),
                ('productUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingValue', models.CharField(max_length=100)),
                ('datePublished', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=10960)),
                ('usedSince', models.CharField(max_length=100)),
                ('reviewBonus', models.CharField(max_length=100)),
                ('reviewMalus', models.CharField(max_length=100)),
                ('reviewTitle', models.CharField(max_length=100)),
                ('reviewReply', models.CharField(max_length=100)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Product')),
            ],
        ),
    ]
