# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDjangoItem',
            fields=[
                ('productId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('last_fetched', models.DateTimeField()),
                ('productUrl', models.URLField()),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('productImageUrl', models.URLField()),
            ],
            options={
                'verbose_name': 'ProductDjangoItem',
            },
        ),
        migrations.CreateModel(
            name='ProductInQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewDjangoItem',
            fields=[
                ('reviewHash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ratingValue', models.IntegerField()),
                ('datePublished', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=10960)),
                ('usedSince', models.CharField(max_length=100)),
                ('reviewBonus', models.CharField(max_length=100)),
                ('reviewMalus', models.CharField(max_length=100)),
                ('reviewTitle', models.CharField(max_length=100)),
                ('reviewReply', models.CharField(max_length=10960)),
                ('fit', models.CharField(max_length=100, null=True)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.ProductDjangoItem')),
            ],
            options={
                'verbose_name': 'ProductReviewDjangoItem',
            },
        ),
    ]
