# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productUrl', models.URLField()),
            ],
        ),
    ]
