# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_productinqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='fit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreview',
            name='reviewReply',
            field=models.CharField(max_length=10960),
        ),
    ]
