# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_auto_20170611_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
