# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_auto_20170611_0241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductDjangoItem',
        ),
        migrations.RenameModel(
            old_name='ProductReview',
            new_name='ProductReviewDjangoItem',
        ),
    ]
