# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_auto_20170611_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdjangoitem',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
