# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0007_productdjangoitem_productprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdjangoitem',
            options={'verbose_name': 'ProductDjangoItem'},
        ),
        migrations.AlterModelOptions(
            name='productreviewdjangoitem',
            options={'verbose_name': 'ProductReviewDjangoItem'},
        ),
        migrations.AddField(
            model_name='productdjangoitem',
            name='productImageUrl',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
