# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0008_auto_20170617_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviewdjangoitem',
            name='id',
        ),
        migrations.AddField(
            model_name='productreviewdjangoitem',
            name='reviewHash',
            field=models.CharField(default='a', max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
